name: Publish @simonheys/wordclock-words

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - 'packages/wordclock-words/**'

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Upgrade npm CLI (OIDC support)
        run: npm i -g npm@11.5.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test package
        run: pnpm --filter @simonheys/wordclock-words test

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
        run: cd packages/wordclock-words && npx semantic-release
